language: ruby
rvm:
  - 2.6.0


install:
 - bundle install 
 - pip install --user html5validator

script: 
  
  - bundle exec jekyll build  
  - htmlproofer --disable-external --allow-hash-href ./_site
  - html5validator --root _site/


sudo: false
